### PR TITLE
update clap derive

### PR DESCRIPTION
**Pull request by blaggacao**
- bump: deps
- update: to use clap-derive (and only use root if necessary)

doing some maintenance while proposing this for NixOS: https://discourse.nixos.org/t/better-wifi-ux-on-the-non-graphical-installer/23030

### CODE REVIEW

**Comment by araujobsd** [comment]
Thank you very much and sorry my delay to merge this.

**Comment by araujobsd** [comment]
@blaggacao Thank you very much for all patches! Could you share with me more information about the proposal you made for NixOS?

Also if you are interested on work with me to maintain ifwifi, I would be more than happy to give you written access to this repository.

**Comment by araujobsd** [comment]
@blaggacao Also, if you guys need any specific feature to make ifwifi as the default cli for NixOS, let me know and I can try to implement it.

Best,

**Comment by blaggacao** [comment]
The result was that we probable should stick with `nmtui`, or some other tool I don't remember, now. Still, I think I'll use iwifi for my personal machines. Thanks for cutting a release!

**Pull request merged**
